import React, { useContext, useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { LanguageContext } from '../App';
import { 
  CheckCircle2, XCircle, MessageSquare, Sparkles, ClipboardCheck, 
  AlertTriangle, Info, Globe, ExternalLink, ArrowLeft, ChevronDown, ChevronUp 
} from 'lucide-react';
import { generateChecklistSteps, calculateReadinessScore, generateAIWarning, getReadinessMessage } from '../utils/aiHelpers';
import './ResultsScreen.css';

const TRANSLATIONS = {
  en: {
    eligible: "You are eligible!",
    notEligible: "Not eligible right now",
    schemeName: "PM Kisan Samman Nidhi",
    benefit: "₹6,000/year in your bank",
    whatThisMeans: "What this means for you",
    poweredBy: "Powered by SahayakAI",
    aiGenerated: "✨ Generated by AI based on your details",
    verifiedByRules: "🧾 Verified using Government Rules",
    explainedByAI: "✨ Explained by AI",
    beforeApply: "Your personalised pre-application checklist",
    checklistSubtext: "Generated based on your details to reduce rejection risk",
    aiInsightLabel: "AI Insight:",
    whyMatters: "Why this matters for you",
    aiWarningTitle: "⚠️ AI Warning",
    whyYouQualify: "Why you qualify while others don't",
    readinessFactors: "Score calculated using 5 risk factors:",
    impossibleWithoutAI: "This explanation adapts automatically for every land size, farmer category, and language.",
    whyRejected: "Why most applications get rejected",
    rejection1: "Aadhaar-bank name mismatch",
    rejection2: "Bank not linked to Aadhaar",
    rejection3: "Wrong farmer category",
    applyPortal: "Apply on PM Kisan Portal",
    checkAnother: "Check Another Scheme",
    disclaimer: "Eligibility verified using official rules. AI explains in simple language.",
    whyNotEligible: "Why you don't qualify",
    whatNext: "What you can do next"
  },
  hi: {
    eligible: "आप पात्र हैं!",
    notEligible: "अभी पात्र नहीं",
    schemeName: "पीएम किसान सम्मान निधि",
    benefit: "आपके बैंक में ₹6,000/वर्ष",
    whatThisMeans: "आपके लिए इसका क्या मतलब है",
    poweredBy: "SahayakAI द्वारा संचालित",
    aiGenerated: "✨ आपके विवरण के आधार पर AI द्वारा उत्पन्न",
    verifiedByRules: "🧾 सरकारी नियमों का उपयोग करके सत्यापित",
    explainedByAI: "✨ AI द्वारा समझाया गया",
    beforeApply: "आपकी व्यक्तिगत पूर्व-आवेदन चेकलिस्ट",
    checklistSubtext: "अस्वीकृति जोखिम कम करने के लिए आपके विवरण के आधार पर उत्पन्न",
    aiInsightLabel: "AI अंतर्दृष्टि:",
    whyMatters: "यह आपके लिए क्यों मायने रखता है",
    aiWarningTitle: "⚠️ AI चेतावनी",
    whyYouQualify: "आप पात्र क्यों हैं जबकि अन्य नहीं",
    readinessFactors: "5 जोखिम कारकों का उपयोग करके स्कोर की गणना:",
    impossibleWithoutAI: "यह स्पष्टीकरण हर भूमि आकार, किसान श्रेणी और भाषा के लिए स्वचालित रूप से अनुकूलित होता है।",
    whyRejected: "अधिकांश आवेदन क्यों अस्वीकार हो जाते हैं",
    rejection1: "आधार-बैंक नाम बेमेल",
    rejection2: "बैंक आधार से लिंक नहीं",
    rejection3: "गलत किसान श्रेणी",
    applyPortal: "पीएम किसान पोर्टल पर आवेदन करें",
    checkAnother: "दूसरी योजना देखें",
    disclaimer: "आधिकारिक नियमों का उपयोग करके पात्रता सत्यापित। AI सरल भाषा में समझाता है।",
    whyNotEligible: "आप पात्र क्यों नहीं हैं",
    whatNext: "आप आगे क्या कर सकते हैं"
  },
  kn: {
    eligible: "ನೀವು ಅರ್ಹರು!",
    notEligible: "ಈಗ ಅರ್ಹರಲ್ಲ",
    schemeName: "PM ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ",
    benefit: "ನಿಮ್ಮ ಬ್ಯಾಂಕಿನಲ್ಲಿ ₹6,000/ವರ್ಷ",
    whatThisMeans: "ಇದು ನಿಮಗೆ ಏನು ಅರ್ಥ",
    poweredBy: "SahayakAI ನಿಂದ ನಡೆಸಲಾಗುತ್ತಿದೆ",
    aiGenerated: "✨ ನಿಮ್ಮ ವಿವರಗಳ ಆಧಾರದ ಮೇಲೆ AI ರಚಿಸಿದೆ",
    verifiedByRules: "🧾 ಸರ್ಕಾರಿ ನಿಯಮಗಳನ್ನು ಬಳಸಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    explainedByAI: "✨ AI ಮೂಲಕ ವಿವರಿಸಲಾಗಿದೆ",
    beforeApply: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಪೂರ್ವ-ಅರ್ಜಿ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ",
    checklistSubtext: "ತಿರಸ್ಕಾರ ಅಪಾಯವನ್ನು ಕಡಿಮೆ ಮಾಡಲು ನಿಮ್ಮ ವಿವರಗಳ ಆಧಾರದ ಮೇಲೆ ರಚಿಸಲಾಗಿದೆ",
    aiInsightLabel: "AI ಒಳನೋಟ:",
    whyMatters: "ಇದು ನಿಮಗೆ ಏಕೆ ಮುಖ್ಯ",
    aiWarningTitle: "⚠️ AI ಎಚ್ಚರಿಕೆ",
    whyYouQualify: "ನೀವು ಅರ್ಹರಾಗಿರುವಾಗ ಇತರರು ಏಕೆ ಅಲ್ಲ",
    readinessFactors: "5 ಅಪಾಯ ಅಂಶಗಳನ್ನು ಬಳಸಿ ಸ್ಕೋರ್ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ:",
    impossibleWithoutAI: "ಈ ವಿವರಣೆಯು ಪ್ರತಿ ಭೂಮಿ ಗಾತ್ರ, ರೈತ ವರ್ಗ ಮತ್ತು ಭಾಷೆಗೆ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ.",
    whyRejected: "ಹೆಚ್ಚಿನ ಅರ್ಜಿಗಳು ಏಕೆ ತಿರಸ್ಕರಿಸಲ್ಪಡುತ್ತವೆ",
    rejection1: "ಆಧಾರ್-ಬ್ಯಾಂಕ್ ಹೆಸರು ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ",
    rejection2: "ಬ್ಯಾಂಕ್ ಆಧಾರ್‌ಗೆ ಲಿಂಕ್ ಆಗಿಲ್ಲ",
    rejection3: "ತಪ್ಪು ರೈತ ವರ್ಗ",
    applyPortal: "PM ಕಿಸಾನ್ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    checkAnother: "ಇನ್ನೊಂದು ಯೋಜನೆ ಪರಿಶೀಲಿಸಿ",
    disclaimer: "ಅಧಿಕೃತ ನಿಯಮಗಳನ್ನು ಬಳಸಿ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ. AI ಸರಳ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸುತ್ತದೆ.",
    whyNotEligible: "ನೀವು ಅರ್ಹರಲ್ಲ ಏಕೆ",
    whatNext: "ನೀವು ಮುಂದೆ ಏನು ಮಾಡಬಹುದು"
  },
  te: {
    eligible: "మీరు అర్హులు!",
    notEligible: "ప్రస్తుతం అర్హులు కాదు",
    schemeName: "PM కిసాన్ సమ్మాన్ నిధి",
    benefit: "మీ బ్యాంకులో ₹6,000/సంవత్సరం",
    whatThisMeans: "ఇది మీకు అర్థం ఏమిటి",
    poweredBy: "SahayakAI ద్వారా అందించబడింది",
    aiGenerated: "✨ మీ వివరాల ఆధారంగా AI రూపొందించింది",
    verifiedByRules: "🧾 ప్రభుత్వ నియమాలను ఉపయోగించి ధృవీకరించబడింది",
    explainedByAI: "✨ AI ద్వారా వివరించబడింది",
    beforeApply: "మీ వ్యక్తిగత పూర్వ-దరఖాస్తు తనిఖీ జాబితా",
    checklistSubtext: "తిరస్కరణ ప్రమాదాన్ని తగ్గించడానికి మీ వివరాల ఆధారంగా రూపొందించబడింది",
    aiInsightLabel: "AI అంతర్దృష్టి:",
    whyMatters: "ఇది మీకు ఎందుకు ముఖ్యం",
    aiWarningTitle: "⚠️ AI హెచ్చరిక",
    whyYouQualify: "మీరు అర్హులు అయితే ఇతరులు ఎందుకు కాదు",
    readinessFactors: "5 ప్రమాద కారకాలను ఉపయోగించి స్కోర్ లెక్కించబడింది:",
    impossibleWithoutAI: "ఈ వివరణ ప్రతి భూమి పరిమాణం, రైతు వర్గం మరియు భాషకు స్వయంచాలకంగా అనుకూలం అవుతుంది.",
    whyRejected: "చాలా దరఖాస్తులు ఎందుకు తిరస్కరించబడతాయి",
    rejection1: "ఆధార్-బ్యాంక్ పేరు సరిపోలడం లేదు",
    rejection2: "బ్యాంక్ ఆధార్‌కు లింక్ చేయబడలేదు",
    rejection3: "తప్పు రైతు వర్గం",
    applyPortal: "PM కిసాన్ పోర్టల్‌లో దరఖాస్తు చేయండి",
    checkAnother: "మరో పథకాన్ని తనిఖీ చేయండి",
    disclaimer: "అధికారిక నియమాలను ఉపయోగించి అర్హత ధృవీకరించబడింది. AI సరళ భాషలో వివరిస్తుంది.",
    whyNotEligible: "మీరు అర్హులు కాని కారణం",
    whatNext: "మీరు తర్వాత ఏమి చేయవచ్చు"
  },
  ta: {
    eligible: "நீங்கள் தகுதியுடையவர்!",
    notEligible: "தற்போது தகுதியற்றவர்",
    schemeName: "PM கிசான் சம்மான் நிதி",
    benefit: "உங்கள் வங்கியில் ₹6,000/ஆண்டு",
    whatThisMeans: "இது உங்களுக்கு என்ன அர்த்தம்",
    poweredBy: "SahayakAI மூலம் இயக்கப்படுகிறது",
    aiGenerated: "✨ உங்கள் விவரங்களின் அடிப்படையில் AI உருவாக்கியது",
    verifiedByRules: "🧾 அரசு விதிகளைப் பயன்படுத்தி சரிபார்க்கப்பட்டது",
    explainedByAI: "✨ AI மூலம் விளக்கப்பட்டது",
    beforeApply: "உங்கள் தனிப்பயன் முன்-விண்ணப்ப சரிபார்ப்பு பட்டியல்",
    checklistSubtext: "நிராகரிப்பு அபாயத்தைக் குறைக்க உங்கள் விவரங்களின் அடிப்படையில் உருவாக்கப்பட்டது",
    aiInsightLabel: "AI நுண்ணறிவு:",
    whyMatters: "இது உங்களுக்கு ஏன் முக்கியம்",
    aiWarningTitle: "⚠️ AI எச்சரிக்கை",
    whyYouQualify: "நீங்கள் தகுதியுடையவர் ஆனால் மற்றவர்கள் ஏன் இல்லை",
    readinessFactors: "5 ஆபத்து காரணிகளைப் பயன்படுத்தி மதிப்பெண் கணக்கிடப்பட்டது:",
    impossibleWithoutAI: "இந்த விளக்கம் ஒவ்வொரு நில அளவு, விவசாயி வகை மற்றும் மொழிக்கும் தானாக மாற்றியமைக்கப்படுகிறது.",
    whyRejected: "பெரும்பாலான விண்ணப்பங்கள் ஏன் நிராகரிக்கப்படுகின்றன",
    rejection1: "ஆதார்-வங்கி பெயர் பொருந்தவில்லை",
    rejection2: "வங்கி ஆதாருடன் இணைக்கப்படவில்லை",
    rejection3: "தவறான விவசாயி வகை",
    applyPortal: "PM கிசான் போர்ட்டலில் விண்ணப்பிக்கவும்",
    checkAnother: "மற்றொரு திட்டத்தை சரிபார்க்கவும்",
    disclaimer: "அதிகாரப்பூர்வ விதிகளைப் பயன்படுத்தி தகுதி சரிபார்க்கப்பட்டது. AI எளிய மொழியில் விளக்குகிறது.",
    whyNotEligible: "நீங்கள் ஏன் தகுதியற்றவர்",
    whatNext: "நீங்கள் அடுத்து என்ன செய்யலாம்"
  },
  mr: {
    eligible: "तुम्ही पात्र आहात!",
    notEligible: "सध्या पात्र नाही",
    schemeName: "PM किसान सम्मान निधी",
    benefit: "तुमच्या बँकेत ₹6,000/वर्ष",
    whatThisMeans: "याचा तुमच्यासाठी अर्थ काय",
    poweredBy: "SahayakAI द्वारे चालवले जाते",
    aiGenerated: "✨ तुमच्या तपशीलांवर आधारित AI ने तयार केले",
    verifiedByRules: "🧾 सरकारी नियमांचा वापर करून सत्यापित",
    explainedByAI: "✨ AI द्वारे स्पष्ट केले",
    beforeApply: "तुमची वैयक्तिक पूर्व-अर्ज तपासणी यादी",
    checklistSubtext: "नाकारण्याचा धोका कमी करण्यासाठी तुमच्या तपशीलांवर आधारित तयार केले",
    aiInsightLabel: "AI अंतर्दृष्टी:",
    whyMatters: "हे तुमच्यासाठी का महत्त्वाचे आहे",
    aiWarningTitle: "⚠️ AI चेतावणी",
    whyYouQualify: "तुम्ही पात्र आहात पण इतर का नाहीत",
    readinessFactors: "5 धोका घटकांचा वापर करून स्कोअर मोजले:",
    impossibleWithoutAI: "हे स्पष्टीकरण प्रत्येक जमीन आकार, शेतकरी श्रेणी आणि भाषेसाठी आपोआप जुळवून घेते.",
    whyRejected: "बहुतेक अर्ज का नाकारले जातात",
    rejection1: "आधार-बँक नाव जुळत नाही",
    rejection2: "बँक आधारशी लिंक नाही",
    rejection3: "चुकीची शेतकरी श्रेणी",
    applyPortal: "PM किसान पोर्टलवर अर्ज करा",
    checkAnother: "दुसरी योजना तपासा",
    disclaimer: "अधिकृत नियमांचा वापर करून पात्रता सत्यापित. AI सोप्या भाषेत स्पष्ट करते.",
    whyNotEligible: "तुम्ही पात्र का नाही",
    whatNext: "तुम्ही पुढे काय करू शकता"
  }
};

const ACTIONABLE_STEPS = {
  GOVT_EMPLOYEE_EXCLUSION: {
    en: [
      "Check if a family member who owns the land and is NOT a government employee can apply",
      "Explore PM Fasal Bima Yojana — available to all farmers",
      "Visit your nearest Common Service Centre (CSC) for guidance"
    ],
    hi: [
      "जांचें कि क्या परिवार का कोई सदस्य जो सरकारी कर्मचारी नहीं है, आवेदन कर सकता है",
      "PM फसल बीमा योजना देखें — सभी किसानों के लिए उपलब्ध",
      "मार्गदर्शन के लिए अपने नजदीकी CSC केंद्र पर जाएं"
    ],
    kn: [
      "ಸರ್ಕಾರಿ ನೌಕರರಲ್ಲದ ಕುಟುಂಬದ ಸದಸ್ಯರು ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದೇ ಎಂದು ಪರಿಶೀಲಿಸಿ",
      "PM ಫಸಲ್ ಬೀಮಾ ಯೋಜನೆಯನ್ನು ಅನ್ವೇಷಿಸಿ — ಎಲ್ಲಾ ರೈತರಿಗೆ ಲಭ್ಯ",
      "ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ ನಿಮ್ಮ ಹತ್ತಿರದ CSC ಕೇಂದ್ರಕ್ಕೆ ಭೇಟಿ ನೀಡಿ"
    ],
    te: [
      "ప్రభుత్వ ఉద్యోగి కాని కుటుంబ సభ్యుడు దరఖాస్తు చేసుకోవచ్చో తనిఖీ చేయండి",
      "PM ఫసల్ బీమా యోజనను అన్వేషించండి — అన్ని రైతులకు అందుబాటులో",
      "మార్గదర్శకత్వం కోసం మీ సమీప CSC కేంద్రాన్ని సందర్శించండి"
    ],
    ta: [
      "அரசு ஊழியர் அல்லாத குடும்ப உறுப்பினர் விண்ணப்பிக்க முடியுமா என சரிபார்க்கவும்",
      "PM பசல் பீமா யோஜனாவை ஆராயுங்கள் — அனைத்து விவசாயிகளுக்கும் கிடைக்கும்",
      "வழிகாட்டுதலுக்கு உங்கள் அருகிலுள்ள CSC மையத்தை பார்வையிடவும்"
    ],
    mr: [
      "सरकारी कर्मचारी नसलेला कुटुंबातील सदस्य अर्ज करू शकतो का ते तपासा",
      "PM फसल बीमा योजना पहा — सर्व शेतकऱ्यांसाठी उपलब्ध",
      "मार्गदर्शनासाठी तुमच्या जवळच्या CSC केंद्राला भेट द्या"
    ]
  },
  NO_LAND_OWNERSHIP: {
    en: [
      "Apply for MGNREGS — guarantees 100 days of paid employment per year",
      "If you recently purchased land, get it officially registered",
      "Contact your Gram Panchayat for MGNREGS registration"
    ],
    hi: [
      "MGNREGS के लिए आवेदन करें — प्रति वर्ष 100 दिन का रोजगार गारंटीड",
      "यदि आपने हाल ही में जमीन खरीदी है, तो इसे आधिकारिक रूप से पंजीकृत करें",
      "MGNREGS पंजीकरण के लिए अपनी ग्राम पंचायत से संपर्क करें"
    ],
    kn: [
      "MGNREGS ಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ — ವರ್ಷಕ್ಕೆ 100 ದಿನಗಳ ಪಾವತಿಸಿದ ಉದ್ಯೋಗ ಖಾತರಿ",
      "ನೀವು ಇತ್ತೀಚೆಗೆ ಭೂಮಿ ಖರೀದಿಸಿದ್ದರೆ, ಅದನ್ನು ಅಧಿಕೃತವಾಗಿ ನೋಂದಾಯಿಸಿ",
      "MGNREGS ನೋಂದಣಿಗಾಗಿ ನಿಮ್ಮ ಗ್ರಾಮ ಪಂಚಾಯತಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ"
    ],
    te: [
      "MGNREGS కోసం దరఖాస్తు చేయండి — సంవత్సరానికి 100 రోజుల చెల్లింపు ఉద్యోగం హామీ",
      "మీరు ఇటీవల భూమిని కొనుగోలు చేసినట్లయితే, దానిని అధికారికంగా నమోదు చేయండి",
      "MGNREGS నమోదు కోసం మీ గ్రామ పంచాయతీని సంప్రదించండి"
    ],
    ta: [
      "MGNREGS க்கு விண்ணப்பிக்கவும் — ஆண்டுக்கு 100 நாட்கள் ஊதிய வேலை உத்தரவாதம்",
      "நீங்கள் சமீபத்தில் நிலம் வாங்கியிருந்தால், அதை அதிகாரப்பூர்வமாக பதிவு செய்யவும்",
      "MGNREGS பதிவுக்கு உங்கள் கிராம பஞ்சாயத்தை தொடர்பு கொள்ளவும்"
    ],
    mr: [
      "MGNREGS साठी अर्ज करा — वर्षाला 100 दिवसांच्या पगाराच्या रोजगाराची हमी",
      "तुम्ही अलीकडे जमीन खरेदी केली असल्यास, ती अधिकृतपणे नोंदणी करा",
      "MGNREGS नोंदणीसाठी तुमच्या ग्राम पंचायतीशी संपर्क साधा"
    ]
  }
};

function ResultsScreen() {
  const navigate = useNavigate();
  const { language } = useContext(LanguageContext);
  const [result, setResult] = useState(null);
  const [showConfetti, setShowConfetti] = useState(false);
  const [expandedSteps, setExpandedSteps] = useState({});
  const [checklistSteps, setChecklistSteps] = useState([]);
  const [readinessScore, setReadinessScore] = useState(0);
  const [aiWarning, setAiWarning] = useState('');
  const [showReadinessInfo, setShowReadinessInfo] = useState(false);

  const t = TRANSLATIONS[language] || TRANSLATIONS.en;

  useEffect(() => {
    const storedResult = sessionStorage.getItem('eligibilityResult');
    if (storedResult) {
      const parsedResult = JSON.parse(storedResult);
      setResult(parsedResult);
      
      if (parsedResult.eligible && parsedResult.userInputs) {
        // Generate personalized checklist
        const steps = generateChecklistSteps(parsedResult.userInputs, language);
        setChecklistSteps(steps);
        
        // Calculate readiness score
        const score = calculateReadinessScore(parsedResult.userInputs);
        setReadinessScore(score);
        
        // Generate AI warning
        const warning = generateAIWarning(parsedResult.userInputs, language);
        setAiWarning(warning);
        
        // Show confetti
        setShowConfetti(true);
        setTimeout(() => setShowConfetti(false), 2000);
      }
    } else {
      navigate('/form');
    }
  }, [navigate, language]);

  const handleCheckAnother = () => {
    sessionStorage.removeItem('eligibilityResult');
    navigate('/scheme');
  };

  const handleApplyNow = () => {
    window.open('https://pmkisan.gov.in', '_blank');
  };

  const handleBack = () => {
    navigate('/form');
  };

  const toggleStepExpansion = (stepId) => {
    setExpandedSteps(prev => ({
      ...prev,
      [stepId]: !prev[stepId]
    }));
  };

  if (!result) {
    return (
      <div className="results-screen-modern">
        <div className="spinner"></div>
      </div>
    );
  }

  return (
    <div className="results-screen-modern animate-fade-in">
      {/* Confetti */}
      {showConfetti && result.eligible && (
        <div className="confetti-container">
          {[...Array(6)].map((_, i) => (
            <div key={i} className={`confetti confetti-${i + 1}`}></div>
          ))}
        </div>
      )}

      <div className="results-container-modern">
        {/* Back Button */}
        <button onClick={handleBack} className="back-button-results">
          <ArrowLeft size={20} />
        </button>

        {result.eligible ? (
          <>
            {/* Success Header */}
            <div className="result-header-success">
              <div className="result-icon-success">
                <CheckCircle2 size={32} />
              </div>
              <h2 className="result-title-success">{t.eligible}</h2>
              
              {/* AI vs Rules Badges */}
              <div className="verification-badges">
                <div className="badge-verified">
                  {t.verifiedByRules}
                </div>
                <div className="badge-ai">
                  {t.explainedByAI}
                </div>
              </div>
              
              <p className="result-scheme-name">{t.schemeName}</p>
              <div className="result-benefit-badge">{t.benefit}</div>
              
              {/* Decorative elements */}
              <div className="decoration decoration-1"></div>
              <div className="decoration decoration-2"></div>
            </div>

            {/* AI Insight */}
            <div className="insight-card">
              <div className="insight-header">
                <MessageSquare size={18} />
                <span>{t.whatThisMeans}</span>
              </div>
              <p className="insight-text">
                {result.explanation || "Great news! You are eligible for PM Kisan Samman Nidhi as a marginal farmer. This scheme provides ₹6,000 annually in three installments. Ensure your Aadhaar is linked to your bank account for DBT."}
              </p>
              <div className="ai-generated-badge">
                <Sparkles size={12} />
                {t.aiGenerated}
              </div>
              <p className="impossible-without-ai">
                {t.impossibleWithoutAI}
              </p>
            </div>

            {/* Why You Qualify Comparison */}
            <div className="comparison-card">
              <h3 className="comparison-title">
                <CheckCircle2 size={16} />
                {t.whyYouQualify}
              </h3>
              <div className="comparison-grid">
                <div className="comparison-item positive">
                  <CheckCircle2 size={14} />
                  <span>{language === 'hi' ? 'भूमि का मालिक' : 'Own land'}</span>
                </div>
                <div className="comparison-item positive">
                  <CheckCircle2 size={14} />
                  <span>{language === 'hi' ? 'सरकारी कर्मचारी नहीं' : 'Not govt employee'}</span>
                </div>
                <div className="comparison-item positive">
                  <CheckCircle2 size={14} />
                  <span>{language === 'hi' ? 'आयकर दाता नहीं' : 'Not tax payer'}</span>
                </div>
                <div className="comparison-item negative">
                  <XCircle size={14} />
                  <span>{language === 'hi' ? 'सरकारी कर्मचारी (सामान्य अस्वीकृति)' : 'Govt employee (common rejection)'}</span>
                </div>
              </div>
            </div>

            {/* Personalized Pre-Application Checklist */}
            <section className="checklist-section">
              <div className="checklist-header">
                <h3 className="section-title-modern">
                  <ClipboardCheck size={18} />
                  {t.beforeApply}
                </h3>
                <p className="checklist-subtext">
                  <Sparkles size={12} />
                  {t.checklistSubtext}
                </p>
              </div>
              
              <div className="checklist-steps">
                {checklistSteps.map((step, index) => (
                  <div key={step.id} className={`checklist-step ${step.priority}`}>
                    <div className="step-header">
                      <div className="step-number-new">{index + 1}</div>
                      <div className="step-content-new">
                        <h4 className="step-title-new">{step.title}</h4>
                        <p className="step-subtitle-new">{step.subtitle}</p>
                      </div>
                    </div>
                    
                    {/* AI Insight */}
                    <div className="ai-insight-box">
                      <Sparkles size={12} className="insight-icon" />
                      <span className="insight-label">{t.aiInsightLabel}</span>
                      <span className="insight-text">{step.aiInsight}</span>
                    </div>
                    
                    {/* Expandable "Why this matters" */}
                    <button 
                      className="why-matters-toggle"
                      onClick={() => toggleStepExpansion(step.id)}
                    >
                      {t.whyMatters}
                      {expandedSteps[step.id] ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                    </button>
                    
                    {expandedSteps[step.id] && (
                      <div className="why-matters-content">
                        {step.whyMatters}
                      </div>
                    )}
                  </div>
                ))}
              </div>
              
              {/* Readiness Indicator */}
              <div className="readiness-indicator">
                <div className="readiness-header">
                  <p className="readiness-text">
                    {getReadinessMessage(readinessScore, language)}
                  </p>
                  <button 
                    className="info-tooltip-trigger"
                    onClick={() => setShowReadinessInfo(!showReadinessInfo)}
                  >
                    <Info size={14} />
                  </button>
                </div>
                <div className="readiness-bar">
                  <div 
                    className="readiness-fill" 
                    style={{ width: `${readinessScore}%` }}
                  ></div>
                </div>
                {showReadinessInfo && (
                  <div className="readiness-factors">
                    <p className="factors-title">{t.readinessFactors}</p>
                    <ul className="factors-list">
                      <li>{language === 'hi' ? '✓ आधार लिंकेज' : '✓ Aadhaar linkage'}</li>
                      <li>{language === 'hi' ? '✓ भूमि रिकॉर्ड' : '✓ Land records'}</li>
                      <li>{language === 'hi' ? '✓ श्रेणी मिलान' : '✓ Category match'}</li>
                      <li>{language === 'hi' ? '✓ बैंक तैयारी' : '✓ Bank readiness'}</li>
                      <li>{language === 'hi' ? '✓ सामान्य अस्वीकृति जोखिम' : '✓ Common rejection risks'}</li>
                    </ul>
                  </div>
                )}
              </div>
            </section>

            {/* AI Warning with Prevention Logic */}
            <div className="ai-warning-box">
              <div className="warning-header">
                <AlertTriangle size={18} />
                <span>{t.aiWarningTitle}</span>
              </div>
              {aiWarning && (
                <div className="warning-prevention-logic">
                  <div className="prevention-item">
                    <p className="prevention-text">{aiWarning.whatGoesWrong}</p>
                  </div>
                  <div className="prevention-item">
                    <p className="prevention-text">{aiWarning.whatToCheck}</p>
                  </div>
                  <div className="prevention-item">
                    <p className="prevention-text">{aiWarning.whenToDo}</p>
                  </div>
                </div>
              )}
            </div>

            {/* Actions */}
            <div className="actions-section">
              <button className="apply-button-modern" onClick={handleApplyNow}>
                <Globe size={20} />
                {t.applyPortal}
                <ExternalLink size={16} />
              </button>
              <button className="secondary-button-modern" onClick={handleCheckAnother}>
                {t.checkAnother}
              </button>
            </div>
          </>
        ) : (
          <>
            {/* Ineligible Header */}
            <div className="result-header-error">
              <div className="result-icon-error">
                <XCircle size={32} />
              </div>
              <h2 className="result-title-error">{t.notEligible}</h2>
              <p className="result-scheme-name">{t.schemeName}</p>
            </div>

            {/* AI Insight */}
            <div className="insight-card">
              <div className="insight-header">
                <MessageSquare size={18} />
                <span>{t.whatThisMeans}</span>
              </div>
              <p className="insight-text">
                {result.explanation}
              </p>
              <div className="insight-footer">
                <Sparkles size={12} />
                {t.poweredBy}
              </div>
            </div>

            {/* Reason */}
            <div className="reason-card">
              <h3 className="reason-title">{t.whyNotEligible}</h3>
              <p className="reason-text">{result.reasonMessage}</p>
            </div>

            {/* Actionable Steps */}
            {ACTIONABLE_STEPS[result.reasonCode] && (
              <div className="actionable-section">
                <h3 className="actionable-title">{t.whatNext}</h3>
                <ul className="actionable-list">
                  {ACTIONABLE_STEPS[result.reasonCode][language]?.map((step, i) => (
                    <li key={i}>{step}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* Actions */}
            <div className="actions-section">
              <button className="secondary-button-modern" onClick={handleCheckAnother}>
                {t.checkAnother}
              </button>
            </div>
          </>
        )}

        {/* Disclaimer */}
        <p className="disclaimer-modern">
          <Info size={12} />
          {t.disclaimer}
        </p>
      </div>
    </div>
  );
}

export default ResultsScreen;
